// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_bVFyANxfWQKuXZauLTV4aGVBHETcw1Y',
    appId: '1:60822638304:web:87b5d03ff829d34b824a85',
    messagingSenderId: '60822638304',
    projectId: 'doctor-appointment-miros',
    authDomain: 'doctor-appointment-miros.firebaseapp.com',
    storageBucket: 'doctor-appointment-miros.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAskIoXppE3OdOEIi_1T9p74cMMk_zWg98',
    appId: '1:60822638304:android:983e52eec0b598a2824a85',
    messagingSenderId: '60822638304',
    projectId: 'doctor-appointment-miros',
    storageBucket: 'doctor-appointment-miros.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOz6_ylUqwxcYCL0ZZq8KMWl6aH9zBnNo',
    appId: '1:60822638304:ios:bb23820dc508db75824a85',
    messagingSenderId: '60822638304',
    projectId: 'doctor-appointment-miros',
    storageBucket: 'doctor-appointment-miros.firebasestorage.app',
    iosBundleId: 'com.example.doctorAppointmentFrontMiros',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOz6_ylUqwxcYCL0ZZq8KMWl6aH9zBnNo',
    appId: '1:60822638304:ios:bb23820dc508db75824a85',
    messagingSenderId: '60822638304',
    projectId: 'doctor-appointment-miros',
    storageBucket: 'doctor-appointment-miros.firebasestorage.app',
    iosBundleId: 'com.example.doctorAppointmentFrontMiros',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_bVFyANxfWQKuXZauLTV4aGVBHETcw1Y',
    appId: '1:60822638304:web:f90bf19f0936d9c7824a85',
    messagingSenderId: '60822638304',
    projectId: 'doctor-appointment-miros',
    authDomain: 'doctor-appointment-miros.firebaseapp.com',
    storageBucket: 'doctor-appointment-miros.firebasestorage.app',
  );
}
